#ifndef BOARD_LAYOUT_H
#define BOARD_LAYOUT_H

#include "stm32g4xx_hal.h"

#define BOARD_LED_LIST(ENTRY) \
    ENTRY(BLUE_1,   GPIOA, GPIO_PIN_5, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH)  \
    ENTRY(BLUE_2,   GPIOA, GPIO_PIN_6, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH)  \
    ENTRY(BLUE_3,   GPIOA, GPIO_PIN_7, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH)  \
    ENTRY(YELLOW_1, GPIOB, GPIO_PIN_6, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH)  \
    ENTRY(YELLOW_2, GPIOC, GPIO_PIN_7, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH)  \
    ENTRY(YELLOW_3, GPIOA, GPIO_PIN_9, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH)  \
    ENTRY(GREEN_1,  GPIOA, GPIO_PIN_8, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_SPEED_FREQ_HIGH)

#define BOARD_BUTTON_LIST(ENTRY) \
    ENTRY(BUTTON_1, GPIOB, GPIO_PIN_10, GPIO_MODE_INPUT, GPIO_PULLUP, GPIO_SPEED_FREQ_LOW)

#endif // BOARD_LAYOUT_H