#ifndef BOARD_LAYOUT_H
#define BOARD_LAYOUT_H

#include "stm32g4xx_hal.h"

// LEDs
#define GPIO_LED_BLUE_1_PIN      (GPIO_PIN_5)
#define GPIO_LED_BLUE_1_PORT     (GPIOA)
#define GPIO_LED_BLUE_1_MODE     (GPIO_MODE_OUTPUT_PP)
#define GPIO_LED_BLUE_1_PULL     (GPIO_PULLUP)
#define GPIO_LED_BLUE_1_SPEED    (GPIO_SPEED_FREQ_HIGH)

#define GPIO_LED_BLUE_2_PIN      (GPIO_PIN_6)
#define GPIO_LED_BLUE_2_PORT     (GPIOA)
#define GPIO_LED_BLUE_2_MODE     (GPIO_MODE_OUTPUT_PP)
#define GPIO_LED_BLUE_2_PULL     (GPIO_PULLUP)
#define GPIO_LED_BLUE_2_SPEED    (GPIO_SPEED_FREQ_HIGH)

#define GPIO_LED_BLUE_3_PIN      (GPIO_PIN_7)
#define GPIO_LED_BLUE_3_PORT     (GPIOA)
#define GPIO_LED_BLUE_3_MODE     (GPIO_MODE_OUTPUT_PP)
#define GPIO_LED_BLUE_3_PULL     (GPIO_PULLUP)
#define GPIO_LED_BLUE_3_SPEED    (GPIO_SPEED_FREQ_HIGH)

#define GPIO_LED_YELLOW_1_PIN    (GPIO_PIN_6)
#define GPIO_LED_YELLOW_1_PORT   (GPIOB)
#define GPIO_LED_YELLOW_1_MODE   (GPIO_MODE_OUTPUT_PP)
#define GPIO_LED_YELLOW_1_PULL   (GPIO_PULLUP)
#define GPIO_LED_YELLOW_1_SPEED  (GPIO_SPEED_FREQ_HIGH)

#define GPIO_LED_YELLOW_2_PIN    (GPIO_PIN_7)
#define GPIO_LED_YELLOW_2_PORT   (GPIOC)
#define GPIO_LED_YELLOW_2_MODE   (GPIO_MODE_OUTPUT_PP)
#define GPIO_LED_YELLOW_2_PULL   (GPIO_PULLUP)
#define GPIO_LED_YELLOW_2_SPEED  (GPIO_SPEED_FREQ_HIGH)

#define GPIO_LED_YELLOW_3_PIN    (GPIO_PIN_9)
#define GPIO_LED_YELLOW_3_PORT   (GPIOA)
#define GPIO_LED_YELLOW_3_MODE   (GPIO_MODE_OUTPUT_PP)
#define GPIO_LED_YELLOW_3_PULL   (GPIO_PULLUP)
#define GPIO_LED_YELLOW_3_SPEED  (GPIO_SPEED_FREQ_HIGH)

#define GPIO_LED_GREEN_1_PIN     (GPIO_PIN_8)
#define GPIO_LED_GREEN_1_PORT    (GPIOA)
#define GPIO_LED_GREEN_1_MODE    (GPIO_MODE_OUTPUT_PP)
#define GPIO_LED_GREEN_1_PULL    (GPIO_PULLUP)
#define GPIO_LED_GREEN_1_SPEED   (GPIO_SPEED_FREQ_HIGH)

// Buttons
#define GPIO_BUTTON_1_PIN        (GPIO_PIN_10)
#define GPIO_BUTTON_1_PORT       (GPIOB)
#define GPIO_BUTTON_1_MODE       (GPIO_MODE_INPUT)
#define GPIO_BUTTON_1_PULL       (GPIO_PULLUP)
#define GPIO_BUTTON_1_SPEED      (GPIO_SPEED_FREQ_HIGH)
#endif // BOARD_LAYOUT_H